# This workflow will do a clean install of node dependencies, build the source code, run tests, and then deploy Google Cloud functions
# NOTE: This should be kept in sync with workflows/node.js.yml - with modifications for triggers.
name: Deploy functions to prod
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]
jobs:
  functions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.2
        with:
          files: |
            packages\/functions\/src\/.+\.ts
            packages\/functions\/scripts\/.+\.ts
            packages\/functions\/package\.json
            packages\/functions\/package\-lock\.json
            packages\/utils\/**
      - name: Cache Firestore emulator
        uses: actions/cache@v2
        env:
          cache-name: cache-firestore-emulator
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-build-v0-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - run: yarn workspaces focus @goldfinch-eng/functions
      - run: yarn workspaces foreach -ptR --from @goldfinch-eng/functions run build
        env:
          NEXT_PUBLIC_GRAPHQL_URL: https://api.thegraph.com/subgraphs/name/goldfinch-eng/goldfinch-v2
          NEXT_PUBLIC_NETWORK_NAME: mainnet
          NEXT_PUBLIC_MAINNET_RPC_URL: https://eth-mainnet.alchemyapi.io/v2/blank
      - run: yarn workspace @goldfinch-eng/functions ci_test
      - name: deploy-prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn workspace @goldfinch-eng/functions exec "yarn ci_functions_config_set_prod && yarn pre-deploy && yarn firebase deploy --only functions --project prod"
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: server-functions-prod
        with:
          environment: production
          sourcemaps: packages/functions/lib/functions
          ignore_empty: true
